//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duoju.Model.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorInfo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Duoju.Model.Resource.ErrorInfo", typeof(ErrorInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this page is forbidden..
        /// </summary>
        public static string Error_403_Message
        {
            get {
                return ResourceManager.GetString("Error_403_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps, You&apos;re lost..
        /// </summary>
        public static string Error_403_Title
        {
            get {
                return ResourceManager.GetString("Error_403_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can not find the page you&apos;re looking for..
        /// </summary>
        public static string Error_404_Message
        {
            get {
                return ResourceManager.GetString("Error_404_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opps, You&apos;re lost..
        /// </summary>
        public static string Error_404_Title
        {
            get {
                return ResourceManager.GetString("Error_404_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this page is forbidden..
        /// </summary>
        public static string Error_405_Message
        {
            get {
                return ResourceManager.GetString("Error_405_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong here. Method not allowed!.
        /// </summary>
        public static string Error_405_Title
        {
            get {
                return ResourceManager.GetString("Error_405_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this page is forbidden..
        /// </summary>
        public static string Error_500_Message
        {
            get {
                return ResourceManager.GetString("Error_500_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something is wrong here. Method not allowed!.
        /// </summary>
        public static string Error_500_Title
        {
            get {
                return ResourceManager.GetString("Error_500_Title", resourceCulture);
            }
        }
    }
}
