insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AF', 'Afghanistan', '阿富汗')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AL', 'Albania', '阿尔巴尼亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('DZ', 'Algeria', '阿尔及利亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AD', 'Andorra', '安道尔')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AO', 'Angola', '安哥拉')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AI', 'Anguilla', '安圭拉岛(英)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AQ', 'Antarctica', '南极洲')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AG', 'Antigua and Barbuda', '安提瓜和巴布达')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AR', 'Argentina', '阿根廷')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AM', 'Armenia', '亚美尼亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AW', 'Aruba', '阿鲁巴岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AU', 'Australia', '澳大利亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AT', 'Austria', '奥地利')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AZ', 'Azerbaijan', '阿塞拜疆')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BS', 'Bahamas', '巴哈马')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BH', 'Bahrain', '巴林')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BD', 'Bangladesh', '孟加拉国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BB', 'Barbados', '巴巴多斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BY', 'Belarus', '白俄罗斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BE', 'Belgium', '比利时')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BZ', 'Belize', '伯利兹')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BJ', 'Benin', '贝宁')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BM', 'Bermuda', '百慕大群岛(英)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BT', 'Bhutan', '不丹')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BO', 'Bolivia', '玻利维亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BA', 'Bosnia and Herzegovina', '波斯尼亚和黑塞哥维那')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BW', 'Botswana', '博茨瓦纳')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BR', 'Brazil', '巴西')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('IO', 'British Indian Ocean Territory', '英属印度洋领地')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BN', 'Brunei', '文莱')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BG', 'Bulgaria', '保加利亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BF', 'Burkina Faso', '布基纳法索')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MM', 'Burma(Myanmar)', '缅甸')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('BI', 'Burundi', '布隆迪')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KH', 'Cambodia(Kampuchea)', '柬埔寨')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CM', 'Cameroon', '喀麦隆')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CA', 'Canada', '加拿大')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CV', 'Cape Verde', '佛得角')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KY', 'Cayman Islands', '开曼群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CF', 'Central African Republic', '中非共和国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TD', 'Chad', '乍得')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CL', 'Chile', '智利')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CN', 'China', '中国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CX', 'Christmas Island', '圣诞岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CC', 'Cocos (Keeling) Islands', '科科斯(基林)群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CO', 'Colombia', '哥伦比亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KM', 'Comoros', '科摩罗')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CG', 'Congo', '刚果')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CK', 'Cook Islands', '库克群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CR', 'Costa Rica', '哥斯达黎加')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CI', 'Cote d''Ivoire', '科特迪瓦')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('HR', 'Croatia', '克罗地亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CU', 'Cuba', '古巴')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CY', 'Cyprus', '塞浦路斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CZ', 'Czech', '捷克')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('DK', 'Denmark', '丹麦')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('DJ', 'Djibouti', '吉布提')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('DM', 'Dominica', '多米尼克')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('DO', 'Dominican Republic', '多米尼加共和国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TP', 'East Timor', '东帝汶')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('EC', 'Ecuador', '厄瓜多尔')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('EG', 'Egypt', '埃及')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SV', 'El Salvador', '萨尔瓦多')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GQ', 'Equatorial Guinea', '赤道几内亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ER', 'Eritrea', '厄立特里亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('EE', 'Estonia', '爱沙尼亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ET', 'Ethiopia', '埃塞俄比亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('FK', 'Falkland Islands (Malvinas)', '福克兰群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('FO', 'Faroe Islands', '法罗群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('FJ', 'Fiji', '斐济')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('FI', 'Finland', '芬兰')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('FR', 'France', '法国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GF', 'French Guiana', '法属圭亚那')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PF', 'French Polynesia', '法属波里尼西亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GA', 'Gabon', '加蓬')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GM', 'Gambia', '冈比亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GE', 'Georgia', '格鲁吉亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('DE', 'Germany', '德国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GH', 'Ghana', '加纳')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GI', 'Gibraltar', '直布罗陀(英)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GR', 'Greece', '希腊')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GL', 'Greenland', '格陵兰岛(丹)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GD', 'Grenada', '格林纳达')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GP', 'Guadeloupe', '瓜德罗普岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GU', 'Guam', '关岛(美)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GT', 'Guatemala', '危地马拉')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GN', 'Guinea', '几内亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GW', 'Guinea-Bissau', '几内亚比绍')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GY', 'Guyana', '圭亚那')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('HT', 'Haiti', '海地')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('HN', 'Honduras', '洪都拉斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('HK', 'Hong Kong', '香港')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('HU', 'Hungary', '匈牙利')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('IS', 'Iceland', '冰岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('IN', 'India', '印度')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ID', 'Indonesia', '印度尼西亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('IR', 'Iran', '伊朗')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('IQ', 'Iraq', '伊拉克')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('IE', 'Ireland', '爱尔兰')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('IL', 'Israel', '以色列')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('IT', 'Italy', '意大利')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('JM', 'Jamaica', '牙买加')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('JP', 'Japan', '日本')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('JO', 'Jordan', '约旦')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KZ', 'Kazakhstan', '哈萨克斯坦')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KE', 'Kenya', '肯尼亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KI', 'Kiribati', '基里巴斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KW', 'Kuwait', '科威特')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KG', 'Kyrgyzstan', '吉尔吉斯斯坦')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LA', 'Lao Peoples'' Democratic Republic', '老挝')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LV', 'Latvia', '拉脱维亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LB', 'Lebanon', '黎巴嫩')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LS', 'Lesotho', '莱索托')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LR', 'Liberia', '利比里亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LY', 'Libya', '利比亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LI', 'Liechtenstein', '列支敦士登')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LT', 'Lithuania', '立陶宛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LU', 'Luxembourg', '卢森堡')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MO', 'Macau', '澳门')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MG', 'Madagascar', '马达加斯加')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MW', 'Malawi', '马拉维')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MY', 'Malaysia', '马来西亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MV', 'Maldives', '马尔代夫')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ML', 'Mali', '马里')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MT', 'Malta', '马耳他')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MH', 'Marshall Islands', '马绍尔群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MQ', 'Martinique', '马提尼克岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MR', 'Mauritania', '毛里塔尼亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MU', 'Mauritius', '毛里求斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('YT', 'Mayotte', '马约特岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MX', 'Mexico', '墨西哥')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('FM', 'Micronesia', '密克罗尼西亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MD', 'Moldova', '摩尔多瓦')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MC', 'Monaco', '摩纳哥')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MN', 'Mongolia', '蒙古')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MNE', 'Montenegro', '黑山共和国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MS', 'Montserrat', '蒙特塞拉特岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MA', 'Morocco', '摩洛哥')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MZ', 'Mozambique', '莫桑比克')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NA', 'Namibia', '纳米比亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NR', 'Nauru', '瑙鲁')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NP', 'Nepal', '尼泊尔')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NL', 'Netherlands', '荷兰')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AN', 'Netherlands Antilles', '荷属安的列斯群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NC', 'New Caledonia', '新喀里多尼亚群岛(法)　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NZ', 'New Zealand', '新西兰')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NI', 'Nicaragua', '尼加拉瓜')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NE', 'Niger', '尼日尔')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NG', 'Nigeria', '尼日利亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NU', 'Niue', '纽埃岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NF', 'Norfolk Island', '诺福克岛(澳)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KP', 'North Korea', '朝鲜')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MP', 'Northern Mariana Islands', '北马里亚纳群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('NO', 'Norway', '挪威')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('OM', 'Oman', '阿曼')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PK', 'Pakistan', '巴基斯坦')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PW', 'Palau', '帕劳')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PS', 'Palestine', '巴勒斯坦')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PA', 'Panama', '巴拿马')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PG', 'Papua New Guinea', '巴布亚新几内亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PY', 'Paraguay', '巴拉圭')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PE', 'Peru', '秘鲁')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PH', 'Philippines', '菲律宾')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PN', 'Pitcairn', '皮特开恩群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PL', 'Poland', '波兰')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PT', 'Portugal', '葡萄牙')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PR', 'Puerto Rico', '波多黎各(美)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('QA', 'Qatar', '卡塔尔')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('MK', 'Republic of Macedonia', '马其顿共和国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('RE', 'Reunion', '留尼汪岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('RO', 'Romania', '罗马尼亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('RU', 'Russia', '俄罗斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('RW', 'Rwanda', '卢旺达')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KN', 'Saint Kitts and Nevis', '圣基茨和尼维斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('VC', 'Saint Vincent and the Grenadines', '圣文森特和格林纳丁斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SM', 'San Marino', '圣马力诺')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ST', 'Sao Tome and Principe', '圣多美和普林西比')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SA', 'Saudi Arabia', '沙特阿拉伯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SN', 'Senegal', '塞内加尔')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SRB', 'Serbia', '塞尔维亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SC', 'Seychelles', '塞舌尔')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SL', 'Sierra Leone', '塞拉利昂')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SG', 'Singapore', '新加坡')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SK', 'Slovakia', '斯洛伐克')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SI', 'Slovenia', '斯洛文尼亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SB', 'Solomon Islands', '所罗门群岛(英)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SO', 'Somalia', '索马里')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ZA', 'South Africa', '南非')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('KR', 'South Korea', '韩国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ES', 'Spain', '西班牙')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LK', 'Sri Lanka', '斯里兰卡')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SH', 'St. Helena', '圣赫勒拿')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('LC', 'St. Lucia', '圣卢西亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('PM', 'St. Pierre and Miquelon', '圣皮埃尔和密克隆群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SD', 'Sudan', '苏丹')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SR', 'Surinam', '苏里南　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SZ', 'Swaziland', '斯威士兰　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SE', 'Sweden', '瑞典　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('CH', 'Switzerland', '瑞士　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('SY', 'Syria', '叙利亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TW', 'Taiwan', '台湾')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TJ', 'Tajikistan', '塔吉克斯坦　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TZ', 'Tanzania', '坦桑尼亚　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TH', 'Thailand', '泰国　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TG', 'Togo', '多哥　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TK', 'Tokelau', '托克劳')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TO', 'Tonga', '汤加　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TT', 'Trinidad and Tobago', '特立尼达和多巴哥')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TN', 'Tunisia', '突尼斯')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TR', 'Turkey', '土耳其')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TM', 'Turkmenistan', '土库曼斯坦　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TC', 'Turks and Caicos Islands', '凯科斯群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('TV', 'Tuvalu', '图瓦卢')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('UG', 'Uganda', '乌干达　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('UA', 'Ukraine', '乌克兰　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('AE', 'United Arab Emirates', '阿联酋')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('GB', 'United Kingdom', '英国　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('US', 'United States', '美国')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('UY', 'Uruguay', '乌拉圭　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('UZ', 'Uzbekistan', '乌兹别克斯坦　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('VU', 'Vanuatu', '瓦努阿图　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('VA', 'Vatican City', '梵蒂冈　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('VE', 'Venezuela', '委内瑞拉　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('VN', 'VietNam', '越南　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('VG', 'Virgin Islands (British)', '维京群岛(英)')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('VI', 'Virgin Islands (U.S.)', '美属维京岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('WF', 'Wallis and Futuna Islands', '瓦利斯和富图纳群岛')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('EH', 'Western Sahara', '西撒哈拉')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('WS', 'Western Samoa', '西萨摩亚')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('YE', 'Yemen', '也门')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('YU', 'Yugoslavia', '南斯拉夫　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ZR', 'Zaire', '扎伊尔　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ZM', 'Zambia', '赞比亚　')
insert into DUOJU$COUNTRIES (COUNTRY_CODE, COUNTRY_NAME, COUNTRY_NAME_CN) values ('ZW', 'Zimbabwe', '津巴布韦　')
