USE [DUOJU]
GO

/****** Object:  Table [dbo].[DUOJU$SUPPLIER]    Script Date: 04/27/2014 23:27:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DUOJU$SUPPLIER](
	[SUPPLIER_ID] [int] IDENTITY(1,1) NOT NULL,
	[PROVINCE_ID] [int] NULL,
	[CITY_ID] [int] NULL,
	[NAME] [nvarchar](255) NULL,
	[ADDRESS] [nvarchar](1000) NULL,
	[TELPHONE] [nvarchar](255) NULL,
	[FAX] [nvarchar](255) NULL,
	[EMAIL] [nvarchar](50) NULL,
	[QQ] [nvarchar](50) NULL,
	[WEBSITE] [nvarchar](100) NULL,
	[LONGITUDE] [decimal](18, 0) NULL,
	[LATITUDE] [decimal](18, 0) NULL,
	[CREATE_BY] [int] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[LAST_UPDATE_BY] [int] NOT NULL,
	[LAST_UPDATE_TIME] [datetime] NOT NULL,
 CONSTRAINT [PK_DUOJU$SUPPLIER] PRIMARY KEY CLUSTERED 
(
	[SUPPLIER_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[DUOJU$SUPPLIERINFO](
	[SUPPLIERINFO_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUPPLIER_ID] [int] NOT NULL,
	[MAINTITLE] [nvarchar](500) NULL,
	[SUBTITLE] [nvarchar](500) NULL,
	[VIEWCOUNT] [int] NULL,
	[PARTYCOUNT] [int] NULL,
	[FAVOURCOUNT] [int] NULL,
	[CONTENT] [nvarchar](max) NULL,
	[CREATE_BY] [int] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[LAST_UPDATE_BY] [int] NOT NULL,
	[LAST_UPDATE_TIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SUPPLIERINFO_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[DUOJU$IMAGECATEGORY](
	[IMAGECATEGORY_ID] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[CREATE_BY] [int] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[LAST_UPDATE_BY] [int] NOT NULL,
	[LAST_UPDATE_TIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IMAGECATEGORY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[DUOJU$IMAGES](
	[IMAGE_ID] [int] IDENTITY(1,1) NOT NULL,
	[IMAGECATEGORY_ID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[URL] [nvarchar](500) NULL,
	[CREATEDDATE] [datetime] NULL,
	[SORTORDER] [int] NULL,
	[CREATE_BY] [int] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[LAST_UPDATE_BY] [int] NOT NULL,
	[LAST_UPDATE_TIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IMAGE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


CREATE TABLE [dbo].[DUOJU$SUPPLIER_IMAGES](
	[SUPPLIERIMAGE_ID] [int] IDENTITY(1,1) NOT NULL,
	[SUPPLIER_ID] [int] NOT NULL,
	[IMAGE_ID] [int] NOT NULL,
	[CREATE_BY] [int] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[LAST_UPDATE_BY] [int] NOT NULL,
	[LAST_UPDATE_TIME] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SUPPLIERIMAGE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


ALTER TABLE [dbo].[DUOJU$SUPPLIER]  WITH CHECK ADD  CONSTRAINT [FK_DUOJU$SUPPLIER_DUOJU$CITIES] FOREIGN KEY([CITY_ID])
REFERENCES [dbo].[DUOJU$CITIES] ([CITY_ID])
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIER] CHECK CONSTRAINT [FK_DUOJU$SUPPLIER_DUOJU$CITIES]
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIER]  WITH CHECK ADD  CONSTRAINT [FK_DUOJU$SUPPLIER_DUOJU$PROVINCES] FOREIGN KEY([PROVINCE_ID])
REFERENCES [dbo].[DUOJU$PROVINCES] ([PROVINCE_ID])
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIER] CHECK CONSTRAINT [FK_DUOJU$SUPPLIER_DUOJU$PROVINCES]
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIERINFO]  WITH CHECK ADD  CONSTRAINT [FK_DUOJU$SUPPLIERINFO_DUOJU$SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[DUOJU$SUPPLIER] ([SUPPLIER_ID])
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIERINFO] CHECK CONSTRAINT [FK_DUOJU$SUPPLIERINFO_DUOJU$SUPPLIER]
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIERINFO] ADD  DEFAULT ((0)) FOR [VIEWCOUNT]
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIERINFO] ADD  DEFAULT ((0)) FOR [PARTYCOUNT]
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIERINFO] ADD  DEFAULT ((0)) FOR [FAVOURCOUNT]
GO

ALTER TABLE [dbo].[DUOJU$IMAGES]  WITH CHECK ADD  CONSTRAINT [FK_DUOJU$IMAGES_DUOJU$IMAGECATEGORY] FOREIGN KEY([IMAGECATEGORY_ID])
REFERENCES [dbo].[DUOJU$IMAGECATEGORY] ([IMAGECATEGORY_ID])
GO

ALTER TABLE [dbo].[DUOJU$IMAGES] CHECK CONSTRAINT [FK_DUOJU$IMAGES_DUOJU$IMAGECATEGORY]
GO

ALTER TABLE [dbo].[DUOJU$IMAGES] ADD  DEFAULT (getdate()) FOR [CREATEDDATE]
GO

ALTER TABLE [dbo].[DUOJU$IMAGES] ADD  DEFAULT ((0)) FOR [SORTORDER]
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIER_IMAGES]  WITH CHECK ADD  CONSTRAINT [FK_DUOJU$SUPPLIER_IMAGES_DUOJU$IMAGES] FOREIGN KEY([IMAGE_ID])
REFERENCES [dbo].[DUOJU$IMAGES] ([IMAGE_ID])
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIER_IMAGES] CHECK CONSTRAINT [FK_DUOJU$SUPPLIER_IMAGES_DUOJU$IMAGES]
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIER_IMAGES]  WITH CHECK ADD  CONSTRAINT [FK_DUOJU$SUPPLIER_IMAGES_DUOJU$SUPPLIER] FOREIGN KEY([SUPPLIER_ID])
REFERENCES [dbo].[DUOJU$SUPPLIER] ([SUPPLIER_ID])
GO

ALTER TABLE [dbo].[DUOJU$SUPPLIER_IMAGES] CHECK CONSTRAINT [FK_DUOJU$SUPPLIER_IMAGES_DUOJU$SUPPLIER]
GO
