//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUOJU_USERS
    {
        public DUOJU_USERS()
        {
            this.DUOJU_USER_CREDITS = new HashSet<DUOJU_USER_CREDITS>();
            this.DUOJU_PARTIES = new HashSet<DUOJU_PARTIES>();
            this.DUOJU_PARTY_COMMENTS = new HashSet<DUOJU_PARTY_COMMENTS>();
            this.DUOJU_PARTY_PARTICIPANTS = new HashSet<DUOJU_PARTY_PARTICIPANTS>();
        }
    
        public int USER_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string PASSWORD { get; set; }
        public int COME_FROM { get; set; }
        public string ROLE { get; set; }
        public string PRIVILEGES { get; set; }
        public string SUBSCRIBED { get; set; }
        public Nullable<System.DateTime> SUBSCRIBE_TIME { get; set; }
        public string OPEN_ID { get; set; }
        public string NICK_NAME { get; set; }
        public string SEX { get; set; }
        public string HEAD_IMG_URL { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> PROVINCE_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public string ENABLED { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public int LAST_UPDATE_BY { get; set; }
        public System.DateTime LAST_UPDATE_TIME { get; set; }
    
        public virtual DUOJU_CITIES DUOJU_CITIES { get; set; }
        public virtual DUOJU_COUNTRIES DUOJU_COUNTRIES { get; set; }
        public virtual DUOJU_PROVINCES DUOJU_PROVINCES { get; set; }
        public virtual DUOJU_ROLE_PRIVILEGES DUOJU_ROLE_PRIVILEGES { get; set; }
        public virtual ICollection<DUOJU_USER_CREDITS> DUOJU_USER_CREDITS { get; set; }
        public virtual ICollection<DUOJU_PARTIES> DUOJU_PARTIES { get; set; }
        public virtual ICollection<DUOJU_PARTY_COMMENTS> DUOJU_PARTY_COMMENTS { get; set; }
        public virtual ICollection<DUOJU_PARTY_PARTICIPANTS> DUOJU_PARTY_PARTICIPANTS { get; set; }
    }
}
