//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOJU.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DUOJU.Domain.Resources.EnumResource", typeof(EnumResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 下午 的本地化字符串。
        /// </summary>
        public static string PartyHoldTimes_AFTERNOON {
            get {
                return ResourceManager.GetString("PartyHoldTimes_AFTERNOON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 早餐 的本地化字符串。
        /// </summary>
        public static string PartyHoldTimes_BREAKFAST {
            get {
                return ResourceManager.GetString("PartyHoldTimes_BREAKFAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晚餐 的本地化字符串。
        /// </summary>
        public static string PartyHoldTimes_DINNER {
            get {
                return ResourceManager.GetString("PartyHoldTimes_DINNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 晚上 的本地化字符串。
        /// </summary>
        public static string PartyHoldTimes_EVENING {
            get {
                return ResourceManager.GetString("PartyHoldTimes_EVENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 午餐 的本地化字符串。
        /// </summary>
        public static string PartyHoldTimes_LUNCH {
            get {
                return ResourceManager.GetString("PartyHoldTimes_LUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 早上 的本地化字符串。
        /// </summary>
        public static string PartyHoldTimes_MORNING {
            get {
                return ResourceManager.GetString("PartyHoldTimes_MORNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消 的本地化字符串。
        /// </summary>
        public static string PartyParticipantStatuses_CANCELED {
            get {
                return ResourceManager.GetString("PartyParticipantStatuses_CANCELED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已删除 的本地化字符串。
        /// </summary>
        public static string PartyParticipantStatuses_DELETED {
            get {
                return ResourceManager.GetString("PartyParticipantStatuses_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已参加 的本地化字符串。
        /// </summary>
        public static string PartyParticipantStatuses_PARTICIPATED {
            get {
                return ResourceManager.GetString("PartyParticipantStatuses_PARTICIPATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已确定 的本地化字符串。
        /// </summary>
        public static string PartyStatuses_CONFIRMED {
            get {
                return ResourceManager.GetString("PartyStatuses_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已消费 的本地化字符串。
        /// </summary>
        public static string PartyStatuses_CONSUMED {
            get {
                return ResourceManager.GetString("PartyStatuses_CONSUMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string PartyStatuses_DELETED {
            get {
                return ResourceManager.GetString("PartyStatuses_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已满额 的本地化字符串。
        /// </summary>
        public static string PartyStatuses_FULLED {
            get {
                return ResourceManager.GetString("PartyStatuses_FULLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已发布 的本地化字符串。
        /// </summary>
        public static string PartyStatuses_PUBLISHED {
            get {
                return ResourceManager.GetString("PartyStatuses_PUBLISHED", resourceCulture);
            }
        }
    }
}
