//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOJU.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DUOJU.Domain.Resources.ModelResource", typeof(ModelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论内容.
        /// </summary>
        public static string CommentPartyInfo_Content {
            get {
                return ResourceManager.GetString("CommentPartyInfo_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聚会说明.
        /// </summary>
        public static string PublishPartyInfo_Description {
            get {
                return ResourceManager.GetString("PublishPartyInfo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聚会日期.
        /// </summary>
        public static string PublishPartyInfo_HoldDate {
            get {
                return ResourceManager.GetString("PublishPartyInfo_HoldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聚会时间段.
        /// </summary>
        public static string PublishPartyInfo_HoldTime {
            get {
                return ResourceManager.GetString("PublishPartyInfo_HoldTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最多参加人数.
        /// </summary>
        public static string PublishPartyInfo_MaxIntoForce {
            get {
                return ResourceManager.GetString("PublishPartyInfo_MaxIntoForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最少参加人数.
        /// </summary>
        public static string PublishPartyInfo_MinIntoForce {
            get {
                return ResourceManager.GetString("PublishPartyInfo_MinIntoForce", resourceCulture);
            }
        }
    }
}
