//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOJU.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUOJU_IDENTIFIER_SETTINGS
    {
        public int IDENTIFIER_SETTING_ID { get; set; }
        public int IDENTIFIER_ID { get; set; }
        public string SETTING_CODE { get; set; }
        public string SETTING_VALUE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public int LAST_UPDATE_BY { get; set; }
        public System.DateTime LAST_UPDATE_TIME { get; set; }
    
        public virtual DUOJU_IDENTIFIERS DUOJU_IDENTIFIERS { get; set; }
    }
}
