//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOJU.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUOJU_USERS
    {
        public DUOJU_USERS()
        {
            this.DUOJU_PARTIES = new HashSet<DUOJU_PARTIES>();
            this.DUOJU_PARTY_COMMENTS = new HashSet<DUOJU_PARTY_COMMENTS>();
            this.DUOJU_PARTY_PARTICIPANTS = new HashSet<DUOJU_PARTY_PARTICIPANTS>();
            this.DUOJU_USER_FINANCES = new HashSet<DUOJU_USER_FINANCES>();
        }
    
        public int USER_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string PASSWORD { get; set; }
        public int SOURCE { get; set; }
        public string ROLE { get; set; }
        public string PRIVILEGES { get; set; }
        public string SUBSCRIBED { get; set; }
        public Nullable<System.DateTime> SUBSCRIBE_TIME { get; set; }
        public string OPEN_ID { get; set; }
        public string NICK_NAME { get; set; }
        public string SEX { get; set; }
        public string HEAD_IMG_URL { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public Nullable<int> PROVINCE_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public string ENABLED { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public int LAST_UPDATE_BY { get; set; }
        public System.DateTime LAST_UPDATE_TIME { get; set; }
    
        public virtual DUOJU_CITIES DUOJU_CITIES { get; set; }
        public virtual DUOJU_COUNTRIES DUOJU_COUNTRIES { get; set; }
        public virtual DUOJU_PROVINCES DUOJU_PROVINCES { get; set; }
        public virtual DUOJU_ROLE_PRIVILEGES DUOJU_ROLE_PRIVILEGES { get; set; }
        public virtual ICollection<DUOJU_PARTIES> DUOJU_PARTIES { get; set; }
        public virtual ICollection<DUOJU_PARTY_COMMENTS> DUOJU_PARTY_COMMENTS { get; set; }
        public virtual ICollection<DUOJU_PARTY_PARTICIPANTS> DUOJU_PARTY_PARTICIPANTS { get; set; }
        public virtual ICollection<DUOJU_USER_FINANCES> DUOJU_USER_FINANCES { get; set; }
    }
}
