//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOJU.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUOJU_PARTIES
    {
        public DUOJU_PARTIES()
        {
            this.DUOJU_PARTY_PARTICIPANTS = new HashSet<DUOJU_PARTY_PARTICIPANTS>();
            this.DUOJU_PARTY_COMMENTS = new HashSet<DUOJU_PARTY_COMMENTS>();
        }
    
        public int PARTY_ID { get; set; }
        public int SUPPLIER_ID { get; set; }
        public int INITIATOR_ID { get; set; }
        public System.DateTime HOLD_DATE { get; set; }
        public int HOLD_TIME { get; set; }
        public string DESCRIPTION { get; set; }
        public int MIN_INTO_FORCE { get; set; }
        public Nullable<int> MAX_INTO_FORCE { get; set; }
        public Nullable<int> CONSUMPTION_VOUCHER_ID { get; set; }
        public int STATUS { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public int LAST_UPDATE_BY { get; set; }
        public System.DateTime LAST_UPDATE_TIME { get; set; }
    
        public virtual DUOJU_USERS DUOJU_USERS { get; set; }
        public virtual ICollection<DUOJU_PARTY_PARTICIPANTS> DUOJU_PARTY_PARTICIPANTS { get; set; }
        public virtual ICollection<DUOJU_PARTY_COMMENTS> DUOJU_PARTY_COMMENTS { get; set; }
        public virtual DUOJU_IDENTIFIERS DUOJU_IDENTIFIERS { get; set; }
    }
}
