//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOJU.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUOJU_COUNTRIES
    {
        public DUOJU_COUNTRIES()
        {
            this.DUOJU_CITIES = new HashSet<DUOJU_CITIES>();
            this.DUOJU_PROVINCES = new HashSet<DUOJU_PROVINCES>();
            this.DUOJU_USERS = new HashSet<DUOJU_USERS>();
        }
    
        public int COUNTRY_ID { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string COUNTRY_NAME { get; set; }
        public string COUNTRY_NAME_CN { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime LAST_UPDATE_TIME { get; set; }
    
        public virtual ICollection<DUOJU_CITIES> DUOJU_CITIES { get; set; }
        public virtual ICollection<DUOJU_PROVINCES> DUOJU_PROVINCES { get; set; }
        public virtual ICollection<DUOJU_USERS> DUOJU_USERS { get; set; }
    }
}
