//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOJU.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUOJU_ROLE_PRIVILEGES
    {
        public DUOJU_ROLE_PRIVILEGES()
        {
            this.DUOJU_USERS = new HashSet<DUOJU_USERS>();
        }
    
        public string ROLE { get; set; }
        public string PRIVILEGES { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public System.DateTime LAST_UPDATE_TIME { get; set; }
    
        public virtual ICollection<DUOJU_USERS> DUOJU_USERS { get; set; }
    }
}
