//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUOJU.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUOJU_SUPPLIER
    {
        public DUOJU_SUPPLIER()
        {
            this.DUOJU_SUPPLIER_IMAGES = new HashSet<DUOJU_SUPPLIER_IMAGES>();
            this.DUOJU_SUPPLIERINFO = new HashSet<DUOJU_SUPPLIERINFO>();
        }
    
        public int SUPPLIER_ID { get; set; }
        public Nullable<int> PROVINCE_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string TELPHONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string QQ { get; set; }
        public string WEBSITE { get; set; }
        public Nullable<decimal> LONGITUDE { get; set; }
        public Nullable<decimal> LATITUDE { get; set; }
        public int CREATE_BY { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public int LAST_UPDATE_BY { get; set; }
        public System.DateTime LAST_UPDATE_TIME { get; set; }
    
        public virtual DUOJU_CITIES DUOJU_CITIES { get; set; }
        public virtual DUOJU_PROVINCES DUOJU_PROVINCES { get; set; }
        public virtual ICollection<DUOJU_SUPPLIER_IMAGES> DUOJU_SUPPLIER_IMAGES { get; set; }
        public virtual ICollection<DUOJU_SUPPLIERINFO> DUOJU_SUPPLIERINFO { get; set; }
    }
}
